"""
plot_rotation_sensitivity.py

Plots R_i = Var_theta(a_i(R_theta x))  (Eq. Ri, sec:rotsens) for the reduced
(2,420-param) model, across layers and configs.

Produces:
  plots_small/repr/rotsens_boxplot_<mode>.png
      -- one boxplot per layer (1..5) of the R_i distribution across all
         neurons in that layer, for a single config. Shows whether R_i
         shrinks (representations become rotation-invariant) as depth
         increases, matching the layer-wise story in sec:finding2.
  plots_small/repr/rotsens_median_comparison.png
      -- median R_i per layer, one line per config, all 5 configs overlaid
         -- directly comparable to the accuracy-comparison plot already
         generated by train_spiking_small.py --compare.
  plots_small/repr/rotsens_temporal_<mode>.png
      -- median-over-neurons R_i(t) vs timestep t, one curve per layer
         (sec:temporal) -- shows whether sensitivity falls off as spikes
         accumulate within a single trial, for spiking layers only.

Usage:
    python3 plot_rotation_sensitivity.py --modes none alternating full hybrid_early hybrid_late \
        --seed 0 --n_per_class 4 --T 50 --models_dir models_small --out_dir plots_small/repr
"""
import os
import argparse
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

from representations_small import (
    load_probe_images, load_model, rotation_sensitivity, MODES,
)

COLORS = {
    "none": "tab:blue", "alternating": "tab:orange", "full": "tab:green",
    "hybrid_early": "tab:red", "hybrid_late": "tab:purple",
}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--modes", nargs="+", default=list(MODES.keys()))
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--n_per_class", type=int, default=4)
    ap.add_argument("--T", type=int, default=50)
    ap.add_argument("--models_dir", default="models_small")
    ap.add_argument("--out_dir", default="plots_small/repr")
    ap.add_argument("--temporal", action="store_true",
                     help="also compute + plot R_i(t) (slower: T forward passes per angle)")
    args = ap.parse_args()

    os.makedirs(args.out_dir, exist_ok=True)
    imgs, labels = load_probe_images(n_per_class=args.n_per_class, seed=args.seed)
    print(f"Loaded {len(imgs)} probe images ({args.n_per_class} per class x {len(set(labels))} classes)")

    all_R = {}  # mode -> layer -> R_i array
    for mode in args.modes:
        print(f"\n=== mode={mode} ===")
        model = load_model(mode, args.seed, models_dir=args.models_dir)
        R, R_t = rotation_sensitivity(model, imgs, T=args.T, per_timestep=args.temporal, seed=args.seed)
        all_R[mode] = R

        # --- per-mode boxplot across layers ---
        layers = sorted(R.keys())
        fig, ax = plt.subplots(figsize=(8, 5))
        ax.boxplot([R[l] for l in layers], labels=[f"L{l}" for l in layers], showfliers=False)
        ax.set_yscale("log")
        ax.set_xlabel("Layer")
        ax.set_ylabel(r"$\mathcal{R}_i$ (log scale)")
        ax.set_title(f"P4CNNSmall [{mode}] rotation sensitivity per neuron, by layer "
                      f"(n={len(imgs)} probe images, params=2420)")
        fig.tight_layout()
        fig.savefig(os.path.join(args.out_dir, f"rotsens_boxplot_{mode}.png"), dpi=150)
        plt.close(fig)
        print(f"  saved rotsens_boxplot_{mode}.png")

        if args.temporal and R_t:
            fig, ax = plt.subplots(figsize=(8, 5))
            for layer_idx in sorted(R_t.keys()):
                med = np.median(R_t[layer_idx], axis=1)  # (T,)
                ax.plot(range(1, len(med) + 1), med, label=f"L{layer_idx}")
            ax.set_xlabel("Timestep t")
            ax.set_ylabel(r"median$_i\ \mathcal{R}_i(t)$")
            ax.set_title(f"P4CNNSmall [{mode}] rotation sensitivity vs. timestep (per layer)")
            ax.legend()
            fig.tight_layout()
            fig.savefig(os.path.join(args.out_dir, f"rotsens_temporal_{mode}.png"), dpi=150)
            plt.close(fig)
            print(f"  saved rotsens_temporal_{mode}.png")

    # --- cross-config median comparison ---
    fig, ax = plt.subplots(figsize=(9, 6))
    for mode in args.modes:
        layers = sorted(all_R[mode].keys())
        medians = [np.median(all_R[mode][l]) for l in layers]
        ax.plot(layers, medians, marker="o", label=mode, color=COLORS.get(mode))
    ax.set_yscale("log")
    ax.set_xlabel("Layer")
    ax.set_ylabel(r"median$_i\ \mathcal{R}_i$ (log scale)")
    ax.set_title("P4CNNSmall: median rotation sensitivity per layer, all configs\n"
                  "(reduced capacity: 5 layers, 4 channels, 2,420 params)")
    ax.legend()
    fig.tight_layout()
    fig.savefig(os.path.join(args.out_dir, "rotsens_median_comparison.png"), dpi=150)
    plt.close(fig)
    print(f"\nSaved rotsens_median_comparison.png to {args.out_dir}")


if __name__ == "__main__":
    main()
